-- Drop tables if they exist in case for resetup
DROP TABLE IF EXISTS FINES CASCADE;
DROP TABLE IF EXISTS BOOK_LOANS CASCADE;
DROP TABLE IF EXISTS BOOK_AUTHORS CASCADE;
DROP TABLE IF EXISTS BORROWER CASCADE;
DROP TABLE IF EXISTS BOOK CASCADE;
DROP TABLE IF EXISTS AUTHORS CASCADE;

-- AUTHORS table
CREATE TABLE AUTHORS (
    author_id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- BOOK table
CREATE TABLE BOOK (
    isbn VARCHAR(13) PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

-- BOOK_AUTHORS junction table (many-to-many)
CREATE TABLE BOOK_AUTHORS (
    author_id INTEGER NOT NULL,
    isbn VARCHAR(13) NOT NULL,
    PRIMARY KEY (author_id, isbn),
    FOREIGN KEY (author_id) REFERENCES AUTHORS(author_id) ON DELETE CASCADE,
    FOREIGN KEY (isbn) REFERENCES BOOK(isbn) ON DELETE CASCADE
);

-- BORROWER table
CREATE TABLE BORROWER (
    card_no SERIAL PRIMARY KEY,
    ssn VARCHAR(11) UNIQUE NOT NULL,
    bname VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(15)
);

-- BOOK_LOANS table
CREATE TABLE BOOK_LOANS (
    loan_id SERIAL PRIMARY KEY,
    isbn VARCHAR(13) NOT NULL,
    card_no INTEGER NOT NULL,
    date_out DATE NOT NULL,
    due_date DATE NOT NULL,
    date_in DATE,
    FOREIGN KEY (isbn) REFERENCES BOOK(isbn) ON DELETE CASCADE,
    FOREIGN KEY (card_no) REFERENCES BORROWER(card_no) ON DELETE CASCADE
);

-- FINES table
CREATE TABLE FINES (
    loan_id INTEGER PRIMARY KEY,
    fine_amt DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (loan_id) REFERENCES BOOK_LOANS(loan_id) ON DELETE CASCADE
);

-- Create indexes
CREATE INDEX idx_book_title ON BOOK(title);
CREATE INDEX idx_author_name ON AUTHORS(name);
CREATE INDEX idx_borrower_name ON BORROWER(bname);
CREATE INDEX idx_book_loans_card ON BOOK_LOANS(card_no);
CREATE INDEX idx_book_loans_isbn ON BOOK_LOANS(isbn);
CREATE INDEX idx_book_loans_date_in ON BOOK_LOANS(date_in);